-   id: stylelint
    name: stylelint
    entry: stylelint
    language: node
    files: \.(css|less)$
    args: []


    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.7.0
